### PR TITLE
Add Apollo config

### PR DESCRIPTION
**Pull request by maarcingebala**
This config allows using the [Apollo GraphQL](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo) extension for VSCode which enables schema introspection and validation within `gql` tags.

image

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).

### CODE REVIEW

**Comment by patrys** [comment]
Couldn't we add the same thing in `package.json` to limit the number of files in the repository root? Awesome change nonetheless! 🔥🔥🔥

**Comment by maarcingebala** [comment]
I used `apollo.config.js` because I wanted to take advantage of `BACKEND_URL` variable.

**Comment by patrys** [comment]
Wouldn't it be more practical to use a named service instead of an environment variable? This way we could publish our schema updates to Apollo Engine and automatically update it in the client without access to a running server instance.

**Comment by maarcingebala** [comment]
True, I haven't thought yet about publishing schema to Apollo Engine, but that's what we will do anyway at some point. Maybe we could merge this PR now so that devs can start using VSCode plugin right away and we will move things to `package.json` later?

**Pull request merged**
