### PR TITLE
Unify base URL and API URI variables; and add build dir and base URL …

### PR DESCRIPTION
**Pull request by airobots**
…environment

I want to merge this change because to unify duplicate variables which causes confusion

### Pull Request Checklist

1. [N/A] All visible strings are translated with proper context.
1. [N/A] All data-formatting is locale-aware (dates, numbers, and so on).
1. [v] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] Changes are mentioned in the changelog.

### Test Environment Config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Review by krzysztofwolski — APPROVED** [review]
Looking good 👍  You probably saved us from debugging in the future, big thank you 🎉

**Comment by krzysztofwolski** [comment]
Changed base from master to feature branch, so we can run tests on Test Environment before merging with master.

**Review by krzysztofwolski — CHANGES_REQUESTED** [review]
@airobots there's an issue with TSC:
https://github.com/mirumee/saleor-storefront/pull/884/checks?check_run_id=1061197793

**Comment by airobots** [comment]
@krzysztofwolski the TSC issues are from the existing codes. I am not sure about those.

Also, some of the TSC issues are related to parseFloat and parseInt that expect string inputs. But parseFloat and parseInt can accept any input. I think that's the issue with the TSC checker.

**Review by dominik-zeglen — CHANGES_REQUESTED** [review]
I'm pretty sure that it throws error because `@next` uses strict null checking while the rest of the project does not, so importing this file in `@next` causes checking this file with strict config.

**Pull request closed without merging**
