### PR TITLE
fix checkout address view

### PR DESCRIPTION
**Pull request by konstantinoschristomanos**
I want to merge this change because...

It fixes the issue #908 

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Comment by orzechdev** [comment]
Checked locally, fix works. Checked Cypress tests locally, which also passed. Nice to see it. Thank you for your contribution!

**Review by orzechdev — APPROVED** [review]

**Review by AlicjaSzu — APPROVED** [review]

**Review by dominik-zeglen — APPROVED** [review]

**Comment by dominik-zeglen** [comment]
Hi, please just add this PR to `CHANGELOG.md` and we'll merge it :)

**Comment by konstantinoschristomanos** [comment]
> Hi, please just add this PR to `CHANGELOG.md` and we'll merge it :)

Done ! Thank you :)

**Comment by krzysztofwolski** [comment]
I'm merging to the Feature branch for QA session

**Pull request merged**
