### PR TITLE
Start using Intl another attempt

### PR DESCRIPTION
**Pull request by przlada**
I want to merge this change because... it adds `react-intl` integration. Basing on the great work of @wael-mohamed PR (#731) I made another clean attempt to localize storefront. I fully agree with @krzysztofwolski (#760) to split this task into smaller ones and resolve issues in smaller modules. I propose to go with three steps:
1. Make strings locale-aware (this PR is an attempt for that)
2. Add functionality to change storefront language and store configuration
3. Load localized model data from Django backend

For now, you can only manually change storefront language (still quite useful) by setting it in `LocaleProvider`. Also for now I only added one additional language (without translation) just for test.

I managed to localize as many strings as I found but some might still be missing. Known things TODO:
- Localizing `AccountMenu` and `AccountMenuMobile` links

Please let me known what do you think about this work and the proposed steps. With your acceptance and guidance, I could try to tackle them.
 

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by przlada** [comment]
Is everything fine with CircleCI config? This PR fails at both (build, cypress/run) steps with `Error: Environment variable API_URI not set` error. Locally it builds successfully

**Comment by krzysztofwolski** [comment]
@przlada thank you a lot for this PR! It looks great. CircleCI failed because we are not running it for forked repos. I'll run tests myself.

**Comment by krzysztofwolski** [comment]
Tests are passing 
image

No other issues when running code myself

**Comment by dominik-zeglen** [comment]
👌💥⭐️

**Comment by dominik-zeglen** [comment]
I added transifex resource for this project, so it's now really translatable :)
https://github.com/mirumee/saleor-storefront/pull/785

**Comment by maarcingebala** [comment]
Hey @przlada, thanks a lot for your contribution! If you're willing to help even more, I think next week we should be able to provide more detailed issues with descriptions of what needs to be done. We already have designs of the language switcher which we'd share with you as well. We need to wait for @krzysztofwolski to return from holiday as he's in charge of the project :)

**Comment by przlada** [comment]
> I added transifex resource for this project, so it's now really translatable :)
> #785
> Oh and I also mentioned you in changelog because I somehow missed that you didn't add yourself there.

That's great, thanks @dominik-zeglen :+1: I added my test Polish translation to Transifex and made PR with it #786

**Comment by przlada** [comment]
> Hey @przlada, thanks a lot for your contribution! If you're willing to help even more, I think next week we should be able to provide more detailed issues with descriptions of what needs to be done. We already have designs of the language switcher which we'd share with you as well. We need to wait for @krzysztofwolski to return from holiday as he's in charge of the project :)

@maarcingebala Yes I'm willing to help :blush: I will patiently wait for @krzysztofwolski. What's the best way to discuss the details? Here on Github or using some different channels?

**Comment by krzysztofwolski** [comment]
@przlada I'm back! On Thursday I'll have github issues for you with designs. Personally I'm fan of async communication on GH, but if there will be any questions I'm open for Hangouts call

**Comment by krzysztofwolski** [comment]
@przlada thanks for patience :) Here is an issue with resources: #798. I suggest to move any questions to that issue. Let me know if you need anything :muscle:

**Pull request merged**
