### PR TITLE
QA for fix checkout address view (#909)

### LINKED ISSUE #908: Checkout shipping and billing address
### What I'm trying to achieve
…
After submitting shipping and billing address as authenticated user, when you go back to checkout/address page the billing address becomes the same as the shipping address.
The bug is only on the view side. When you go to checkout/review you can see that the addresses has been correctly submitted 
### Steps to reproduce the problem
1. checkout, choose different shipping and billing address and then submit the form 
2. go back to checkout/address and you see that the billing address that you chose has changed to the shipping one

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Browser:

### PR DESCRIPTION
**Pull request by krzysztofwolski**
Original PR: #909 by @Konstantinos

* fix checkout address view

Co-authored-by: “Konstantinos <“kostas.christomanos@gmail.com”>

I want to merge this change because...

Fixes #908

### Test Environment Config

API_URI=https://master.staging.saleor.rocks/graphql/

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-1172 Bug with billing address handling](https://app.clickup.com/t/2549495/SALEOR-1172)

**Review by mlamperski — APPROVED** [review]
Tested positive. Couldn't reproduce reported behavior after fix.

**Comment by krzysztofwolski** [comment]
@konstantinoschristomanos All tests green 😎  Thank you! 💪

**Comment by konstantinoschristomanos** [comment]
> @konstantinoschristomanos All tests green 😎 Thank you! 💪

You are welcome @krzysztofwolski ! :)

**Pull request merged**
